{
  den,
  lib,
  inputs,
  config,
  ...
}:
{
  imports = [ inputs.den.flakeModule ];

  den.hosts.x86_64-linux.igloo.users.tux = { };

  den.aspects.igloo = {
    # User TODO: Remove for real host
    nixos.fileSystems."/".device = "/dev/no-boot";
    nixos.fileSystems."/".fsType = "auto";
    nixos.boot.loader.grub.enable = false;
  };

  den.aspects.tux = {
    includes = [ den.provides.define-user ];
    user.description = "Bird";

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) cowsay;
      };

    tests =
      { tux, ... }:
      {
        test-tux-is-bird = {
          expr = tux.description;
          expected = "Bird";
        };
      };
  };

  # Enter flake-parts scope from flake-system (inherits { system }).
  # This integrates the flake-parts resolution into the main pipeline
  # so we don't need a separate den.lib.aspects.resolve call.
  den.policies.to-flake-parts =
    { system, ... }:
    [
      (den.lib.policy.resolve.to "flake-parts" {
        flake-parts = {
          name = "flake-parts-${system}";
          aspect = { };
        };
      })
    ];
  den.schema.flake-system.includes = [ den.policies.to-flake-parts ];

  # Collect the assembled flake-parts class and store as a module list.
  den.policies.collect-flake-parts = _: [
    (den.lib.policy.instantiate {
      name = "flake-parts";
      class = "flake-parts";
      instantiate = { modules, ... }: modules;
      intoAttr = [ "denPerSystem" ];
    })
  ];

  # Walk flake-level aspects in the flake-parts scope.
  # Class files add their own routes via den.schema.flake-parts.includes.
  den.schema.flake-parts.isEntity = true;
  den.schema.flake-parts.includes = [
    den.aspects.foo
    den.policies.collect-flake-parts
  ];

  den.aspects.foo = {
    includes = [ den.aspects.bar ];

    treefmt.settings.on-unmatched = "warn";

    devshell.commands = [ { package = "cowsay"; } ];

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) htop;
      };
  };

  den.aspects.bar = {
    treefmt.programs.nixfmt.enable = true;

    tests.test-math-works = {
      expr = 22 * 2;
      expected = 44;
    };

    packages =
      { config, ... }:
      {
        write-files = config.files.writer.drv;
      };

    files =
      { pkgs, ... }:
      {
        files = [
          {
            path_ = "README.md";
            drv = pkgs.writeText "README.md" ''
              # Example Den custom classes for flake-parts modules and perSystem outputs.

              This example showcases Den forward classes for third-party flake-parts modules.

              This README is generated by `nix run .#write-files`.

              See den.nix and flake-parts.nix
            '';
          }
        ];
      };

    devshell =
      { pkgs, self', ... }:
      {
        commands = [
          {
            package = self'.packages.write-files;
          }
        ];
        packages = [
          pkgs.hello
        ];
      };

  };

}
