{
  den,
  lib,
  inputs,
  config,
  ...
}:
{
  # --- Class declarations ---
  # Framework already registers `packages`; declare the rest.
  den.classes = {
    treefmt = { };
    devshell = { };
    files = { };
    tests = { };
  };

  # --- Host setup ---
  den.hosts.x86_64-linux.igloo.users.tux = { };

  den.aspects.igloo = {
    # User TODO: Remove for real host
    nixos.fileSystems."/".device = "/dev/no-boot";
    nixos.fileSystems."/".fsType = "auto";
    nixos.boot.loader.grub.enable = false;
  };

  den.aspects.tux = {
    includes = [ den.provides.define-user ];
    user.description = "Bird";

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) cowsay;
      };

    tests =
      { tux, ... }:
      {
        test-tux-is-bird = {
          expr = tux.description;
          expected = "Bird";
        };
      };
  };

  # --- Flake-level aspects ---
  den.aspects.foo = {
    includes = [ den.aspects.bar ];

    treefmt.settings.on-unmatched = "warn";

    devshell.commands = [ { package = "cowsay"; } ];

    packages =
      { pkgs, ... }:
      {
        inherit (pkgs) htop;
      };
  };

  den.aspects.bar = {
    treefmt.programs.nixfmt.enable = true;

    tests.test-math-works = {
      expr = 22 * 2;
      expected = 44;
    };

    packages =
      { config, ... }:
      {
        write-files = config.files.writer.drv;
      };

    files =
      { pkgs, ... }:
      {
        files = [
          {
            path_ = "README.md";
            drv = pkgs.writeText "README.md" ''
              # Example Den custom classes for flake-parts modules and perSystem outputs.

              This example showcases Den forward classes for third-party flake-parts modules.

              This README is generated by `nix run .#write-files`.

              See den.nix and flake-parts.nix
            '';
          }
        ];
      };

    devshell =
      { pkgs, self', ... }:
      {
        commands = [
          {
            package = self'.packages.write-files;
          }
        ];
        packages = [
          pkgs.hello
        ];
      };
  };

  # --- Pipeline wiring ---
  # Walk flake-level aspects at flake-system scope (context = { system }).
  # Function modules won't be wrapped with den args — they receive
  # perSystem args when imported into flake-parts.
  den.schema.flake-system.includes = [
    den.aspects.foo
    den.policies.collect-perSystem
  ];

  # Exclude framework's packages route — it evaluates eagerly with only
  # { pkgs }, breaking modules that need perSystem config.
  # flake-parts handles packages output via perSystem automatically.
  den.schema.flake-system.excludes = [ den.policies.to-packages ];

  # Collect each custom class into flake.denModules.<system>.<class>.
  # Fires once per system. policy.instantiate (with sourceScopeId fallback)
  # collects from the full flake-system subtree including host/user scopes.
  den.policies.collect-perSystem =
    { system, ... }:
    map
      (
        cls:
        den.lib.policy.instantiate {
          name = "${cls}-${system}";
          class = cls;
          instantiate = { modules, ... }: modules;
          intoAttr = [
            "denModules"
            system
            cls
          ];
        }
      )
      [
        "treefmt"
        "devshell"
        "files"
        "tests"
        "packages"
      ];
}
